if: branch !~ ^v\d
language: node_js
node_js: node
jobs:
  include:
  - dist: xenial
    addons:
      snaps: chromium
  - os: osx
    addons:
      chrome: stable
    script: node test.js
  - os: windows
    before_install: choco install googlechrome
    script: node test.js
